# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#	USE A DOCKER-COMPOSE.YML IN THE EXAMPLE DIRECTORY
#
# THIS IS A WORKING FILE
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



version: '3.7'

services:

# =============================================================
#
#	TRAEFIK - reverse proxy
#
# =============================================================

  reverse-proxy:
    image: traefik:v2.2.1
    container_name: reverse-proxy
    command:
      # - "--log.level=DEBUG"
      # - "--api.dashboard=true"
      # - "--api.insecure=false"
      - "--providers.file.directory=/FileProvider/"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web-secure.address=:443"
      - "--serverstransport.insecureskipverify=true"
      - "--certificatesresolvers.certificato.acme.dnschallenge=true"
      - "--certificatesresolvers.certificato.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.certificato.acme.dnschallenge.delaybeforecheck=10"
      - "--certificatesresolvers.certificato.acme.dnschallenge.resolvers=1.1.1.1:53"
      # - "--certificatesresolvers.certificato.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.certificato.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.certificato.acme.storage=acme.json"
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_API_KEY: ${CF_API_KEY}
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}
    container_name: traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
    #   - "traefik.http.routers.api.entrypoints=web-secure"
    #   - "traefik.http.routers.api.tls.certresolver=certificato"
    #   - "traefik.http.routers.api.tls.domains[0].main=*.${DOMAIN}"
    #   - "traefik.http.routers.api.service=api@internal"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events
      - /volume1/docker/traefik/acme.json:/acme.json
      - /volume1/docker/traefik/FileProvider/:/FileProvider/
    restart: always


# =============================================================
#
#	WHOAMI - test webserver
#
# =============================================================

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web-secure"
      - "traefik.http.routers.whoami.tls.certresolver=certificato"
      - "traefik.http.routers.whoami.tls.domains[0].main=*.${DOMAIN}"
      - 'traefik.http.routers.whoami.middlewares=authelia@docker'


# =============================================================

#	PORTAINER
#
# =============================================================

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    labels:
      #	HTTPS traffic
      - "traefik.enable=true"
      - "traefik.http.routers.portainerS.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainerS.entrypoints=web-secure"
      - "traefik.http.routers.portainerS.tls=true"
      - "traefik.http.routers.portainerS.tls.certresolver=certificato"
      - "traefik.http.routers.portainerS.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.portainerS.service=portainerService"
      - "traefik.http.services.portainerService.loadBalancer.server.port=9000"


# =============================================================
#
#	GRAFANA
#
# =============================================================

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      # - grafana-storage:/var/lib/grafana
      - /volume1/docker/grafana/data:/var/lib/grafana
      # - /volume1/docker/grafana/log:/var/log/grafana
    labels:
      #	HTTPS traffic
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`pm8.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=web-secure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=certificato"
      - "traefik.http.routers.grafana.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.grafana.service=grafanaService"
      - "traefik.http.services.grafanaService.loadBalancer.server.port=3000"
      - 'traefik.http.routers.grafana.middlewares=authelia@docker'

    environment:
      - GF_SERVER_ROOT_URL=https://pm8.${DOMAIN}
      - GF_SERVER_DOMAIN=${DOMAIN}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ASSIGN_ORG=true
      - GF_USERS_ASSIGN_ORG_ROLE=Editor
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=Remote-User
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true

    restart: always


# =============================================================
#
#	INFLUXDB
#
# =============================================================

  influx:
    image: influxdb
    container_name: influx
    volumes:
      - /volume1/docker/pm8_data:/var/lib/influxdb
    ports:
      - 8086:8086
    labels:
      #	HTTPS traffic
      - "traefik.enable=true"
      - "traefik.http.routers.influxS.rule=Host(`influx.${DOMAIN}`)"
      - "traefik.http.routers.influxS.entrypoints=web-secure"
      - "traefik.http.routers.influxS.tls=true"
      - "traefik.http.routers.influxS.tls.certresolver=certificato"
      - "traefik.http.routers.influxS.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.influxS.service=influxService"
      - "traefik.http.services.influxService.loadBalancer.server.port=8086"
    restart: always
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ADMIN_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}



# =============================================================
#
#	NODERED
#
# =============================================================

  nodered:
    image: nodered/node-red
    container_name: nodered
    volumes:
      # - nodered-storage:/data
      # - /volume1/docker/nodered/conifg/settings.js:/data/settings.js
      - /volume1/docker/nodered/dati:/data/
    labels:
      #	HTTPS traffic
      - "traefik.enable=true"
      - "traefik.http.routers.noderedS.rule=Host(`nodered.${DOMAIN}`)"
      - "traefik.http.routers.noderedS.entrypoints=web-secure"
      - "traefik.http.routers.noderedS.tls=true"
      - "traefik.http.routers.noderedS.tls.certresolver=certificato"
      - "traefik.http.routers.noderedS.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.noderedS.service=noderedService"
      # - "traefik.http.routers.noderedS.middlewares=noderedMdlS"
      # - "traefik.http.middlewares.noderedMdlS.basicauth.users=${BASIC_AUTH}"
      - 'traefik.http.routers.noderedS.middlewares=authelia@docker'
      - "traefik.http.services.noderedService.loadBalancer.server.port=1880"
    restart: always




# =============================================================
#
#	OUROBOROS
#
# =============================================================

  aggiornamento:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=3600
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=Europe/Zurich
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock




# =============================================================
#
#	AUTHELIA
#
# =============================================================

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /volume1/docker/authelia:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.${DOMAIN}`)'
      - 'traefik.http.routers.authelia.entrypoints=web-secure'
      - 'traefik.http.routers.authelia.tls=true'
      - "traefik.http.routers.authelia.tls.certresolver=certificato"
      - "traefik.http.routers.authelia.tls.domains[0].main=*.${DOMAIN}"
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN}/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'
    # ports:
    #   - 9091:9091
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE}


# =============================================================
#
#	UNIFI CONTROLLER
#
# =============================================================

  unifi:
    image: goofball222/unifi
    container_name: unifi
    volumes:
      - /volume1/docker/unifi/data:/usr/lib/unifi/data
      - /volume1/docker/unifi/logs:/usr/lib/unifi/logs
    ports:
      - 10001:10001/udp
      - 3478:3478/udp
      - 8080:8080
    labels:
      #	HTTPS traffic
      - "traefik.enable=true"
      - "traefik.http.routers.unifiS.rule=Host(`controller.${DOMAIN}`)"
      - "traefik.http.routers.unifiS.entrypoints=web-secure"
      - "traefik.http.routers.unifiS.tls=true"
      - "traefik.http.routers.unifiS.tls.certresolver=certificato"
      - "traefik.http.routers.unifiS.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.unifiS.service=UnifiService"
      - "traefik.http.services.UnifiService.loadBalancer.server.port=8443"
      - "traefik.http.services.UnifiService.loadbalancer.server.scheme=https"
    environment:
      - TZ=UTC
      - JVM_INIT_HEAP_SIZE=256M
      - JVM_MAX_HEAP_SIZE=512M
    restart: always

# =============================================================
#
#	HOME ASSISTANT
#
# =============================================================

  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    volumes:
      - /volume1/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeaut.rule=Host(`bosco.${DOMAIN}`)'
      - 'traefik.http.routers.homeaut.entrypoints=web-secure'
      - 'traefik.http.routers.homeaut.tls=true'
      - "traefik.http.routers.homeaut.tls.certresolver=certificato"
      - "traefik.http.routers.homeaut.tls.domains[0].main=*.${DOMAIN}"
      - "traefik.http.routers.homeaut.service=homeautService"
      - "traefik.http.services.homeautService.loadBalancer.server.port=8123"
    # ports:
    #   - 9091:9091
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE}

# =============================================================
#
#	MOSQUITTO
#
# =============================================================

  # mosquitto:
  #   image: homeassistant/home-assistant:stable
  #   container_name: home-assistant
  #   volumes:
  #     - /volume1/docker/home-assistant:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.homeaut.rule=Host(`bosco.${DOMAIN}`)'
  #     - 'traefik.http.routers.homeaut.entrypoints=web-secure'
  #     - 'traefik.http.routers.homeaut.tls=true'
  #     - "traefik.http.routers.homeaut.tls.certresolver=certificato"
  #     - "traefik.http.routers.homeaut.tls.domains[0].main=*.${DOMAIN}"
  #     - "traefik.http.routers.homeaut.service=homeautService"
  #     - "traefik.http.services.homeautService.loadBalancer.server.port=8123"
  #   # ports:
  #   #   - 9091:9091
  #   restart: unless-stopped
  #   environment:
  #     - TZ=${TIME_ZONE}

volumes:

  grafana-storage:

  nodered-storage:
