[tls.options]

  [tls.options.default]
    minVersion = "VersionTLS12"

    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
    ]

    sniStrict = true

  [tls.options.myTLSOptions]
    [tls.options.myTLSOptions.clientAuth]
		caFiles = ["client.crt"]
		clientAuthType = "RequireAndVerifyClientCert"

[http]
  # Add the router
  [http.routers]
    [http.routers.hassio]
      entryPoints = ["web-secure"]
      service = "service-hassio"
      rule = "Host(`ha.example.org`)"     #Cambiare con il proprio dominio
      certresolver="certificato"
      options="myTLSOptions@file"
      [[http.routers.hassio.tls.domains]]
        main = "*.example.org"              #Cambiare con il proprio dominio

  # Add the service
    [http.services.service-hassio]
      [http.services.service-hassio.loadBalancer]
        [[http.services.service-hassio.loadBalancer.servers]]
          url = "http://192.168.1.123:8123"
